# Generated by Django 6.0.1 on 2026-01-16 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JosekiTree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ツリー名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="削除フラグ"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="削除日時"
                    ),
                ),
            ],
            options={
                "verbose_name": "定跡ツリー",
                "verbose_name_plural": "定跡ツリー",
                "db_table": "joseki_trees",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sfen",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="SFEN（手数なし）"
                    ),
                ),
                ("ply", models.IntegerField(default=0, verbose_name="手数")),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "evaluation",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="評価値（centipawn）"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="メタデータ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="trees.josekitree",
                        verbose_name="所属ツリー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ノード",
                "verbose_name_plural": "ノード",
                "db_table": "nodes",
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "move_usi",
                    models.CharField(max_length=10, verbose_name="USI形式の指し手"),
                ),
                (
                    "move_japanese",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="日本語表記の指し手"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_edges",
                        to="trees.node",
                        verbose_name="子ノード",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_edges",
                        to="trees.node",
                        verbose_name="親ノード",
                    ),
                ),
            ],
            options={
                "verbose_name": "エッジ",
                "verbose_name_plural": "エッジ",
                "db_table": "edges",
            },
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("tree", "sfen"), name="unique_node_per_tree_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("parent", "move_usi"), name="unique_move_from_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("child")), _negated=True),
                name="no_self_reference",
            ),
        ),
    ]
