# Generated by Django 6.0.1 on 2026-01-16 08:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ラベル名"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="色は #RRGGBB 形式で指定してください",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                        verbose_name="表示色（HEX）",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "ラベル",
                "verbose_name_plural": "ラベル",
                "db_table": "labels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NodeLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_labels",
                        to="labels.label",
                        verbose_name="ラベル",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_labels",
                        to="trees.node",
                        verbose_name="ノード",
                    ),
                ),
            ],
            options={
                "verbose_name": "ノード-ラベル関連",
                "verbose_name_plural": "ノード-ラベル関連",
                "db_table": "node_labels",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("node", "label"), name="unique_label_per_node"
                    )
                ],
            },
        ),
    ]
